name: lenali
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.3

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  network_info_plus: ^6.1.4
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.0
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  flutter_webrtc: ^0.14.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.0
  flutter_background_service_android: ^6.3.0
 
  device_info_plus: ^11.4.0
  file_picker: ^10.1.9
 
  flutter_local_notifications: ^19.2.0
  path_provider: ^2.1.5


  open_file: ^3.5.10
  flutter_sound: ^9.28.0
  audioplayers: ^6.4.0
  video_player: ^2.9.5
  flutter_background_service: ^5.1.0
  sqflite: ^2.4.2
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/icon/icon.png"
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/started.png
