name: lenali
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.3

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  network_info_plus: ^6.1.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.8
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  flutter_webrtc: ^0.13.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  lan_scanner: ^4.0.0+1
  device_info_plus: ^11.4.0
  file_picker: ^10.1.2
  web_socket_channel: ^3.0.3
  flutter_form_builder: ^10.0.1
  form_builder_file_picker: ^5.0.0
  multi_image_picker_view: ^3.0.0
  form_builder_image_picker: ^4.3.1
  file: ^7.0.1
  flutter_local_notifications: ^19.1.0
  path_provider: ^2.1.5


  open_file: ^3.5.10
  mime: ^2.0.0
  udp: ^5.0.3
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  nearby_connections: ^4.3.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  sqflite: ^2.4.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/started.png
